<div id="ww-custom-slider">
    <div class="item">
        <img src="https://picsum.photos/1440/420"/>
        <img class="mobile" src="https://picsum.photos/760/420"/>
    </div>
    <div class="item">
        <img src="https://picsum.photos/1440/420"/>
        <img class="mobile" src="https://picsum.photos/760/420"/>
    </div>
    <div class="item">
        <img src="https://picsum.photos/1440/420"/>
        <img class="mobile" src="https://picsum.photos/760/420"/>
    </div>
</div>

<script type="text/x-magento-init">
{
"body" :
  {
     "customSlider": {}
  }
}
</script>
