<div id="ww-custom-slider">
    <div class="item">
        <img src="https://placeimg.com/1440/420/tech"/>
        <img class="mobile" src="https://placeimg.com/760/420/tech"/>
    </div>
    <div class="item">
        <img src="https://placeimg.com/1440/420/tech"/>
        <img class="mobile" src="https://placeimg.com/760/420/tech"/>
    </div>
    <div class="item">
        <img src="https://placeimg.com/1440/420/tech"/>
        <img class="mobile" src="https://placeimg.com/760/420/tech"/>
    </div>
</div>

<script type="text/x-magento-init">
{
"body" :
  {
     "customSlider": {}
  }
}
</script>
